# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_token',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
