# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='already_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='application_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='program',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploaded/'),
        ),
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='supporting_files',
            field=models.FileField(blank=True, null=True, upload_to='uploaded/'),
        ),
        migrations.AddField(
            model_name='account',
            name='supporting_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='team_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='want_to_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
