# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160402_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='already_done',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='application_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='program',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='school',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='supporting_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='team_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='want_to_do',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='year_of_study',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
