# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160402_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='application_status',
            field=models.CharField(blank=True, default='Profile Incomplete', max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
    ]
