# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160402_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='team_code',
        ),
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
