# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160402_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.TextField(default='[]'),
        ),
    ]
