# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.TextField(default='{}'),
        ),
    ]
