# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160402_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
