# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160403_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_token',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
