# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160403_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='application_status',
            field=models.CharField(blank=True, default='Profile incomplete', max_length=64),
        ),
    ]
