# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 04:11
from __future__ import unicode_literals

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160403_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.main.models.upload_to_handler),
        ),
        migrations.AlterField(
            model_name='account',
            name='supporting_files',
            field=models.FileField(blank=True, null=True, upload_to=apps.main.models.upload_to_handler),
        ),
    ]
