# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160407_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activation_token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
    ]
